### ISSUE TITLE
vATIS profiles don't match to the reality on the APCH type

### ISSUE THREAD

**Issue by YuchenChien** [vatsimhk/Hong-Kong-Sector-Package#120]
![image](https://github.com/user-attachments/assets/7d6ee6f2-e7b9-402e-aab0-6c83cc375b8a)
![image](https://github.com/user-attachments/assets/2ac3a645-897c-45be-875c-67a260143c38)

The former one is what Lim filed on discord previously, the latter one is from HKIA.
Realworld is using EXP ILS **APCH** instead of ILS **APP** stated on the vATIS.
Hopefully it will be updated with the corresponding type as rw.

**Comment by Limyyyyy** [comment]
Hi, CAD changes the format every day and I'm still observing whats the newest "trend". Will try to keep it up to date.

**Comment by EightSmart** [comment]
SOP has been updated to not use preset ARPT COND, controllers should now directly copy the real world ATIS conditions into the free form ARPT COND text box.
