### ISSUE TITLE
VMMC Proc. Code wrong

### ISSUE THREAD

**Issue by AaronZSAM101** [vatsimhk/Hong-Kong-Sector-Package#36]
VMMC SOUSA2P/16 has a wrong waypoint in ese file. (Sector Version 2309v1)

Here is the code:
```
SID:VMMC:16:SOUSA2P:PAPA MULET SKATE OGAN SOUSA
```
This code is located in line 245, after checking with HKAIP (AIRAC 2309), `OGAN` is not in the procedure.
![image](https://github.com/vatsimhk/Hong-Kong-Sector-Package/assets/60245950/2a4faa6c-1797-4100-9f0e-709cd764ef3d)

**Comment by EightSmart** [comment]
Solved in commit 4ffab25, will be integrated in 2310 v1

**Comment by EightSmart** [comment]
Fixed in #39
