### ISSUE TITLE
VMMC Procedure wrong

### ISSUE THREAD

**Issue by AaronZSAM101** [vatsimhk/Hong-Kong-Sector-Package#56]
`NLG7A` pass a wrong waypoint.
![image](https://github.com/vatsimhk/Hong-Kong-Sector-Package/assets/60245950/2823871e-c2a1-49a2-a177-482ea3ee8294)

Reference to AIP Macao, the next waypoint for NLG-7A after NLG is LATOP, not ZUH. Please consider to fix in the sector~

![image](https://github.com/vatsimhk/Hong-Kong-Sector-Package/assets/60245950/f58b4f95-34c9-4c5e-9c1b-4b84fc78cfd2)

**Comment by EightSmart** [comment]
Fixed in 2402 v1
