### ISSUE TITLE
Macau Controller info

### ISSUE THREAD

**Issue by AaronZSAM101** [vatsimhk/Hong-Kong-Sector-Package#89]
For the code in `LoginProfiles.txt`, ATC position profiles related to Macau are shown as below:
```
PROFILE:VMMC_DEL:20:2
ATIS2:"Macau Delivery"
ATIS3:Up to date Charts & Procedures - www.ais.gov.hk
ATIS4:Give feedback on my service - hq.vat-sea.com/atc/feedback
PROFILE:VMMC_GND:20:3
ATIS2:"Macau Ground"
ATIS3:Up to date Charts & Procedures - www.ais.gov.hk
ATIS4:Give feedback on my service - hq.vat-sea.com/atc/feedback
PROFILE:VMMC_TWR:50:4
ATIS2:"Macau Tower"
ATIS3:Up to date Charts & Procedures - www.ais.gov.hk
ATIS4:Give feedback on my service - hq.vat-sea.com/atc/feedback
PROFILE:VMMC_APP:150:5
ATIS2:"Hong Kong Radar" (Macau Sector)
ATIS3:VMMC ATIS on 126.400 | Up to date Charts & Procedures - www.ais.gov.hk
ATIS4:Give feedback on my service - hq.vat-sea.com/atc/feedback
```
As we can see, [HK AIP](www.ais.gov.hk) only provides the information related to Hong Kong airspace, other information are refer to  [Macau AIP](https://www.aacm.gov.mo/index.php?r=reference/fly&pageid=98). Is there any possible to change the link to Macau AIP so that the flight crews and controller can get the information about VMMC directly?

![image](https://github.com/user-attachments/assets/e153de06-0438-493c-8db2-05ff831509b9)
![image](https://github.com/user-attachments/assets/2caf9eb7-61b4-42e3-8dfe-11e4594f38e6)

**Comment by Limyyyyy** [comment]
@EightSmart or we change the link to https://vathk.com/en/charts/airport

**Comment by AaronZSAM101** [comment]
LC's comment would be the best choice, include all the charts related to HK airspace
