### ISSUE TITLE
Building Sector

### ISSUE THREAD

**Issue by earthjasonlin** [vatsimhk/Hong-Kong-Sector-Package#9]
Hi,
How do you build your sectors, do you use a program to parse navdata or just finish it line by line?
Thanks

**Comment by EightSmart** [comment]
Hi,
Most minor amendments are just done line by line. The base package was generated by Aeronav GNG but we have since moved away from using them for our sector files

**Comment by earthjasonlin** [comment]
OK, I see.
Thanks very much
